# Generated by Django 2.1.3 on 2018-11-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_and_categories', '0006_auto_20181123_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoriesId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products_and_categories.Category'),
        ),
    ]
