# Generated by Django 2.1.3 on 2018-11-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_and_categories', '0009_auto_20181126_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categoriesId',
        ),
        migrations.AddField(
            model_name='category',
            name='categoriesId',
            field=models.ManyToManyField(blank=True, null=True, related_name='_category_categoriesId_+', to='products_and_categories.Category'),
        ),
    ]
