# Generated by Django 2.1.3 on 2018-11-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_and_categories', '0010_auto_20181129_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categoriesId',
        ),
        migrations.AddField(
            model_name='category',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='_category_categories_+', to='products_and_categories.Category'),
        ),
    ]
