# Generated by Django 2.1.3 on 2018-11-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_and_categories', '0011_auto_20181129_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
