# Generated by Django 4.1 on 2022-08-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_and_categories', '0013_alter_category_categories_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
