# Generated by Django 4.1 on 2022-08-08 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_and_categories', '0015_alter_category_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_reversed', to='products_and_categories.category'),
        ),
    ]
